@@PLS_UTILITY.pkh
@@P_BASE.pkh
@@P_CONTEXT.pkh
@@P_LANGUAGE.pkh
@@P_LOCATION.pkh
@@P_MESSAGE.pkh
@@P_SYSTEM_PARAMETER.pkh
@@P_SYSTEM_USER.pkh
@@P_TEXT.pkh
@@P_TEXT_TYPE.pkh

@@PLS_UTILITY.pkb
@@P_BASE.pkb
@@P_CONTEXT.pkb
@@P_LANGUAGE.pkb
@@P_LOCATION.pkb
@@P_MESSAGE.pkb
@@P_SYSTEM_PARAMETER.pkb
@@P_SYSTEM_USER.pkb
@@P_TEXT.pkb
@@P_TEXT_TYPE.pkb
