@@PLS_UTILITY.pkh
@@TEXT.pkh
@@MESSAGE.pkh
@@TEXT_TYPE.pkh
@@LANGUAGE.pkh
@@SYSTEM_PARAMETER.pkh
@@SYSTEM_USER.pkh
@@PSR_CONTEXT.pkh

@@PLS_UTILITY.pkb
@@TEXT.pkb
@@MESSAGE.pkb
@@TEXT_TYPE.pkb
@@LANGUAGE.pkb
@@SYSTEM_PARAMETER.pkb
@@SYSTEM_USER.pkb
@@PSR_CONTEXT.pkb
