--
-- ASR_RETURNEES - Refugee and refugee-like returnees
--
create or replace view ASR_RETURNEES as
with Q_ASR_RETURNEES as
 (select ASR_YEAR, DST_ID, LOC_ID_ASYLUM_COUNTRY, LOC_ID_ORIGIN_COUNTRY, STG_ID_PRIMARY,
    REFRTN_VALUE, REFRTN_STC_ID, REFRTN_VERSION_NBR, REFRTN_ITM_ID,
    REFRTN_AH_VALUE, REFRTN_AH_STC_ID, REFRTN_AH_VERSION_NBR, REFRTN_AH_ITM_ID
  from
   (select to_char(extract(year from STC.START_DATE)) as ASR_YEAR, STC.DST_ID,
      STC.LOC_ID_ASYLUM_COUNTRY, STC.LOC_ID_ORIGIN_COUNTRY, STC.STG_ID_PRIMARY,
      STC.STCT_CODE,
      STC.VALUE,
      STC.ID as STC_ID,
      STC.VERSION_NBR,
      STC.ITM_ID
    from T_STATISTIC_TYPES_IN_GROUPS STTIG
    inner join T_STATISTICS STC
      on STC.STCT_CODE = STTIG.STCT_CODE
    where STTIG.STTG_CODE = 'RETURNEE')
  pivot
   (sum(VALUE) as VALUE, max(STC_ID) as STC_ID, max(VERSION_NBR) as VERSION_NBR,
      max(ITM_ID) as ITM_ID
    for STCT_CODE
    in ('REFRTN' as REFRTN,
        'REFRTN-AH' as REFRTN_AH))),
--
Q_LOCATIONS as
 (select ID, NAME
  from
   (select LOC.ID, TXT.TEXT as NAME,
      row_number() over
       (partition by LOC.ID
        order by LANG.ACTIVE_FLAG desc, nvl(ULP.PREF_SEQ, LANG.DISPLAY_SEQ + 1e5)) as RANK
    from T_LOCATIONS LOC
    inner join T_TEXT_ITEMS TXT
      on TXT.ITM_ID = LOC.ITM_ID
      and TXT.TXTT_CODE = 'NAME'
      and TXT.SEQ_NBR = 1
    inner join T_LANGUAGES LANG
      on LANG.CODE = TXT.LANG_CODE
    left outer join T_USER_LANGUAGE_PREFERENCES ULP
      on ULP.LANG_CODE = TXT.LANG_CODE
      and ULP.USERID = sys_context('PSR', 'USERID'))
  where RANK = 1),
--
Q_DISPLACEMENT_STATUSES as
 (select ID, DESCRIPTION, CODE
  from
   (select DST.ID, TXT.TEXT DESCRIPTION, DST.CODE,
      row_number() over
       (partition by DST.ID
        order by LANG.ACTIVE_FLAG desc, nvl(ULP.PREF_SEQ, LANG.DISPLAY_SEQ + 1e5)) as RANK
    from T_DISPLACEMENT_STATUSES DST
    inner join T_TEXT_ITEMS TXT
      on TXT.ITM_ID = DST.ITM_ID
      and TXT.TXTT_CODE = 'DESCR'
      and TXT.SEQ_NBR = 1
    inner join T_LANGUAGES LANG
      on LANG.CODE = TXT.LANG_CODE
    left outer join T_USER_LANGUAGE_PREFERENCES ULP
      on ULP.LANG_CODE = TXT.LANG_CODE
      and ULP.USERID = sys_context('PSR', 'USERID'))
  where RANK = 1)
--
select cast(RET.ASR_YEAR as varchar2(4)) as ASR_YEAR,
  RET.LOC_ID_ORIGIN_COUNTRY,
  cast(LOCA1.CHAR_VALUE as varchar2(3)) as ISO_ORIGIN_CODE,
  cast(LOCA2.CHAR_VALUE as varchar2(3)) as UNHCR_ORIGIN_CODE,
  LOC1.NAME as LOC_NAME_ORIGIN_COUNTRY,
  RET.DST_ID, DST.DESCRIPTION as DST_DESCRIPTION, DST.CODE as DST_CODE,
  RET.LOC_ID_ASYLUM_COUNTRY,
  cast(LOCA3.CHAR_VALUE as varchar2(3)) as ISO_COUNTRY_CODE,
  cast(LOCA4.CHAR_VALUE as varchar2(3)) as UNHCR_COUNTRY_CODE,
  LOC2.NAME as LOC_NAME_ASYLUM_COUNTRY,
  RET.STG_ID_PRIMARY, STG.VERSION_NBR as STG_VERSION_NBR, STG.ITM_ID as STG_ITM_ID,
  cast(STGA1.CHAR_VALUE as varchar2(10)) as SOURCE, STGA1.VERSION_NBR as STGA_VERSION_NBR_SOURCE,
  STGA1.ITM_ID as STGA_ITM_ID_SOURCE,
  cast(STGA2.CHAR_VALUE as varchar2(10)) as BASIS, STGA2.VERSION_NBR as STGA_VERSION_NBR_BASIS,
  STGA2.ITM_ID as STGA_ITM_ID_BASIS,
  RET.REFRTN_VALUE, RET.REFRTN_STC_ID, RET.REFRTN_VERSION_NBR, RET.REFRTN_ITM_ID,
  RET.REFRTN_AH_VALUE, RET.REFRTN_AH_STC_ID, RET.REFRTN_AH_VERSION_NBR, RET.REFRTN_AH_ITM_ID
from Q_ASR_RETURNEES RET
inner join Q_LOCATIONS LOC1
  on LOC1.ID = RET.LOC_ID_ORIGIN_COUNTRY
left outer join T_LOCATION_ATTRIBUTES LOCA1
  on LOCA1.LOC_ID = LOC1.ID
  and LOCA1.LOCAT_CODE = 'IS03166A3'
left outer join T_LOCATION_ATTRIBUTES LOCA2
  on LOCA2.LOC_ID = LOC1.ID
  and LOCA2.LOCAT_CODE = 'HCRCC'
left outer join Q_LOCATIONS LOC2
  on LOC2.ID = RET.LOC_ID_ASYLUM_COUNTRY
left outer join T_LOCATION_ATTRIBUTES LOCA3
  on LOCA3.LOC_ID = LOC2.ID
  and LOCA3.LOCAT_CODE = 'IS03166A3'
left outer join T_LOCATION_ATTRIBUTES LOCA4
  on LOCA4.LOC_ID = LOC2.ID
  and LOCA4.LOCAT_CODE = 'HCRCC'
inner join Q_DISPLACEMENT_STATUSES DST
  on DST.ID = RET.DST_ID
left outer join T_STATISTIC_GROUPS STG
  on STG.ID = RET.STG_ID_PRIMARY
left outer join T_STC_GROUP_ATTRIBUTES STGA1
  on STGA1.STG_ID = STG.ID
  and STGA1.STGAT_CODE = 'SOURCE'
left outer join T_STC_GROUP_ATTRIBUTES STGA2
  on STGA2.STG_ID = STG.ID
  and STGA2.STGAT_CODE = 'BASIS';
