execute P_STATISTIC_TYPE.INSERT_STATISTIC_GROUP('ASR', 'en', 'Annual Statistics Report');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_GROUP('STOCK', 'en', 'Stock statistics');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_GROUP('FLOW', 'en', 'Flow statistics');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOP', 'en', 'Population of persons of concern');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOP');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOP');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCASSIST', 'en', 'Persons of concern assisted by UNHCR');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCASSIST');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCASSIST');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('ASYFI', 'en', 'Asylum-seekers applied during year (first instance)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'ASYFI');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('FLOW', 'ASYFI');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPR', 'en', 'Population of persons of concern (Registration basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPR');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPR');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPRE', 'en', 'Population of persons of concern (Registration and estimate basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPRE');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPRE');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPRS', 'en', 'Population of persons of concern (Registration and survey basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPRS');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPRS');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPC', 'en', 'Population of persons of concern (Census basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPC');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPC');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPE', 'en', 'Population of persons of concern (Estimate basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPE');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPE');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPS', 'en', 'Population of persons of concern (Survey basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPS');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPS');

execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE('POCPOPO', 'en', 'Population of persons of concern (Other/various basis)');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('ASR', 'POCPOPO');
execute P_STATISTIC_TYPE.INSERT_STATISTIC_TYPE_GROUPING('STOCK', 'POCPOPO');
