variable LOC_ID1 number;
variable LOC_ID2 number;
variable VERSION_NBR number

-- Location types
execute P_LOCATION.INSERT_LOCATION_TYPE('COUNTRY', 'en', 'Country');
execute P_LOCATION.INSERT_LOCATION_TYPE('OTHORIGIN', 'en', 'Other Origin');
execute P_LOCATION.INSERT_LOCATION_TYPE('UNREG', 'en', 'UN Region');
execute P_LOCATION.INSERT_LOCATION_TYPE('UNSUBREG', 'en', 'UN Subregion');
execute P_LOCATION.INSERT_LOCATION_TYPE('HCRBUR', 'en', 'UNHCR Bureau');
execute P_LOCATION.INSERT_LOCATION_TYPE('HCRREGOP', 'en', 'UNHCR Regional Operation');
execute P_LOCATION.INSERT_LOCATION_TYPE('POINT', 'en', 'Point');
execute P_LOCATION.INSERT_LOCATION_TYPE('ADMIN1', 'en', 'Level 1 administrative division');
execute P_LOCATION.INSERT_LOCATION_TYPE('ADMIN2', 'en', 'Level 2 administrative division');

-- Location attribute types
execute P_LOCATION.INSERT_LOCATION_ATTRIBUTE_TYPE('IS03166A3', 'C', 'en', 'ISO 3166-1 Alpha-3 country code');
execute P_LOCATION.INSERT_LOCATION_ATTRIBUTE_TYPE('IS03166A2', 'C', 'en', 'ISO 3166-1 Alpha-2 country code');
execute P_LOCATION.INSERT_LOCATION_ATTRIBUTE_TYPE('IS03166NUM', 'C', 'en', 'ISO 3166-1 Numeric country code');
execute P_LOCATION.INSERT_LOCATION_ATTRIBUTE_TYPE('UNHCRCC', 'C', 'en', 'UNHCR country code');
execute P_LOCATION.INSERT_LOCATION_ATTRIBUTE_TYPE('IS03166_2', 'C', 'en', 'ISO 3166-2 subdivision code');

-- Location relationship types
execute P_LOCATION.INSERT_LOC_RELATIONSHIP_TYPE('WITHIN', 'en', 'Divided into / Within');
execute P_LOCATION.INSERT_LOC_RELATIONSHIP_TYPE('RESP', 'en', 'Responsible for / Reports to');

-- UN Regions and Subregions (from CommonDataHub "ISO 3166 Country Codes")
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Africa', 'UNREG');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Eastern Africa', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Middle Africa', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Northern Africa', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Southern Africa', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Western Africa', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Americas', 'UNREG');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Caribbean', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Central America', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Northern America', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'South America', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Asia', 'UNREG');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Central Asia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Eastern Asia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'South-Eastern Asia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Southern Asia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Western Asia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Europe', 'UNREG');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Eastern Europe', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Northern Europe', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Southern Europe', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Western Europe', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Oceania', 'UNREG');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Australia and New Zealand', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Melanesia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Micronesia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Polynesia', 'UNSUBREG');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'WITHIN');

-- UNHCR Regional Bureaux and Operations (from UNHCR Global Trends 2010 Annexes, Table 26)
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Africa', 'HCRBUR');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Central Africa and the Great Lakes (CA-GL)', 'HCRREGOP');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'RESP');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'East and Horn of Africa (EHA)', 'HCRREGOP');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'RESP');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'Southern Africa (SAO)', 'HCRREGOP');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'RESP');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID2, 'en', 'West Africa (WA)', 'HCRREGOP');
execute P_LOCATION.INSERT_LOCATION_RELATIONSHIP(:LOC_ID1, :LOC_ID2, 'RESP');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Middle East and North Africa (MENA)', 'HCRBUR');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'The Americas (RBAC)', 'HCRBUR');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Asia and Pacific (RBAP)', 'HCRBUR');
execute P_LOCATION.INSERT_LOCATION(:LOC_ID1, 'en', 'Europe (RBE)', 'HCRBUR');
