declare
  nID P_BASE.tnDST_ID;
begin
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Refugees', 'REF', pnDISPLAY_SEQ => 1);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Persons in a refugee-like situation', 'ROC', pnDISPLAY_SEQ => 2);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Asylum seekers', 'ASY', pnDISPLAY_SEQ => 3);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Returned refugees', 'RET', pnDISPLAY_SEQ => 4);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Repatriated refugees', 'RPT', pnDISPLAY_SEQ => 5);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Internally displaced persons', 'IDP', pnDISPLAY_SEQ => 6);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Persons in an IDP-like situation', 'IOC', pnDISPLAY_SEQ => 7);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Persons returned from an IDP or IDP-like situation', 'RDP', pnDISPLAY_SEQ => 8);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Stateless persons', 'STA', pnDISPLAY_SEQ => 9);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Others of concern', 'OOC', pnDISPLAY_SEQ => 10);
  P_DISPLACEMENT_STATUS.INSERT_DISPLACEMENT_STATUS(nID, 'en', 'Refugees and asylum seekers', 'RAS');
end;
/
