--
-- ASR_POC_SUMMARY_EN
--
create materialized view ASR_POC_SUMMARY_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  REFPOP_VALUE, REFPOP_REDACTED_FLAG, ASYPOP_VALUE, ASYPOP_REDACTED_FLAG,
  REFRTN_VALUE, REFRTN_REDACTED_FLAG,
  IDPHPOP_VALUE, IDPHPOP_REDACTED_FLAG, IDPHRTN_VALUE, IDPHRTN_REDACTED_FLAG,
  STAPOP_VALUE, STAPOP_REDACTED_FLAG, OOCPOP_VALUE, OOCPOP_REDACTED_FLAG
from V_ASR_POC_SUMMARY_EN;

create index IX_POCSE_YEAR on ASR_POC_SUMMARY_EN (ASR_YEAR);
create index IX_POCSE_COU_RES on ASR_POC_SUMMARY_EN (COU_CODE_RESIDENCE);
create index IX_POCSE_COU_OGN on ASR_POC_SUMMARY_EN (COU_CODE_ORIGIN);

grant select on ASR_POC_SUMMARY_EN to PSR_PUBLIC_QUERY;

--
-- ASR_POC_DETAILS_EN
--
create materialized view ASR_POC_DETAILS_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  POPULATION_TYPE_CODE, POPULATION_TYPE_EN, POPULATION_TYPE_SEQ, VALUE, REDACTED_FLAG
from V_ASR_POC_DETAILS_EN;

create index IX_POCDE_YEAR on ASR_POC_DETAILS_EN (ASR_YEAR);
create index IX_POCDE_COU_RES on ASR_POC_DETAILS_EN (COU_CODE_RESIDENCE);
create index IX_POCDE_COU_OGN on ASR_POC_DETAILS_EN (COU_CODE_ORIGIN);
create index IX_POCDE_COU_PTC on ASR_POC_DETAILS_EN (POPULATION_TYPE_CODE);

grant select on ASR_POC_DETAILS_EN to PSR_PUBLIC_QUERY;

--
-- ASR_DEMOGRAPHICS_EN
--
create materialized view ASR_DEMOGRAPHICS_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, LOC_NAME_RESIDENCE_EN,
  --COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN, DST_CODE, DST_DESCRIPTION_EN,
  F0_VALUE, F0_REDACTED_FLAG, F5_VALUE, F5_REDACTED_FLAG, F12_VALUE, F12_REDACTED_FLAG,
  F18_VALUE, F18_REDACTED_FLAG, F60_VALUE, F60_REDACTED_FLAG, FOTHER_VALUE, FOTHER_REDACTED_FLAG,
  FTOTAL_VALUE, FTOTAL_REDACTED_FLAG,
  M0_VALUE, M0_REDACTED_FLAG, M5_VALUE, M5_REDACTED_FLAG, M12_VALUE, M12_REDACTED_FLAG,
  M18_VALUE, M18_REDACTED_FLAG, M60_VALUE, M60_REDACTED_FLAG, MOTHER_VALUE, MOTHER_REDACTED_FLAG,
  MTOTAL_VALUE, MTOTAL_REDACTED_FLAG, TOTAL_VALUE, TOTAL_REDACTED_FLAG
from V_ASR_DEMOGRAPHICS_EN;

create index IX_DEME_YEAR on ASR_DEMOGRAPHICS_EN (ASR_YEAR);
create index IX_DEME_COU_RES on ASR_DEMOGRAPHICS_EN (COU_CODE_RESIDENCE);
--create index IX_DEME_COU_OGN on ASR_DEMOGRAPHICS_EN (COU_CODE_ORIGIN);

grant select on ASR_DEMOGRAPHICS_EN to PSR_PUBLIC_QUERY;

--
-- ASR_RSD_EN
--
create materialized view ASR_RSD_EN as
select ASR_YEAR, COU_CODE_ASYLUM, COU_NAME_ASYLUM_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  RSD_PROC_TYPE_CODE, RSD_PROC_TYPE_DESCRIPTION_EN,
  RSD_PROC_LEVEL_CODE, RSD_PROC_LEVEL_DESCRIPTION_EN,
  ASYPOP_START_VALUE, ASYPOP_START_REDACTED_FLAG,
  ASYPOP_AH_START_VALUE, ASYPOP_AH_START_REDACTED_FLAG,
  ASYAPP_VALUE, ASYAPP_REDACTED_FLAG,
  ASYREC_CV_VALUE, ASYREC_CV_REDACTED_FLAG,
  ASYREC_CP_VALUE, ASYREC_CP_REDACTED_FLAG,
  ASYREJ_VALUE, ASYREJ_REDACTED_FLAG,
  ASYOTHCL_VALUE, ASYOTHCL_REDACTED_FLAG,
  ASYPOP_END_VALUE, ASYPOP_END_REDACTED_FLAG,
  ASYPOP_AH_END_VALUE, ASYPOP_AH_END_REDACTED_FLAG
from V_ASR_RSD_EN;

create index IX_RSDE_YEAR on ASR_RSD_EN (ASR_YEAR);
create index IX_RSDE_COU_ASY on ASR_RSD_EN (COU_CODE_ASYLUM);
create index IX_RSDE_COU_OGN on ASR_RSD_EN (COU_CODE_ORIGIN);

grant select on ASR_RSD_EN to PSR_PUBLIC_QUERY;