--
-- ASR_POC_SUMMARY_EN
--
create materialized view ASR_POC_SUMMARY_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  REFPOP_VALUE, ASYPOP_VALUE, REFRTN_VALUE, IDPHPOP_VALUE, IDPHRTN_VALUE, STAPOP_VALUE, OOCPOP_VALUE
from V_ASR_POC_SUMMARY_EN;

create index IX_POCSE_YEAR on ASR_POC_SUMMARY_EN (ASR_YEAR);
create index IX_POCSE_COU_RES on ASR_POC_SUMMARY_EN (COU_CODE_RESIDENCE);
create index IX_POCSE_COU_OGN on ASR_POC_SUMMARY_EN (COU_CODE_ORIGIN);

--
-- ASR_POC_DETAILS_EN
--
create materialized view ASR_POC_DETAILS_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  POPULATION_TYPE_CODE, POPULATION_TYPE_EN, POPULATION_TYPE_SEQ, VALUE
from V_ASR_POC_DETAILS_EN;

create index IX_POCDE_YEAR on ASR_POC_DETAILS_EN (ASR_YEAR);
create index IX_POCDE_COU_RES on ASR_POC_DETAILS_EN (COU_CODE_RESIDENCE);
create index IX_POCDE_COU_OGN on ASR_POC_DETAILS_EN (COU_CODE_ORIGIN);
create index IX_POCDE_COU_PTC on ASR_POC_DETAILS_EN (POPULATION_TYPE_CODE);

--
-- ASR_DEMOGRAPHICS_EN
--
create materialized view ASR_DEMOGRAPHICS_EN as
select ASR_YEAR, COU_CODE_RESIDENCE, COU_NAME_RESIDENCE_EN, LOC_NAME_RESIDENCE_EN,
  COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN, DST_CODE, DST_DESCRIPTION_EN,
  F0_VALUE, F5_VALUE, F12_VALUE, F18_VALUE, F60_VALUE, FOTHER_VALUE, FTOTAL_VALUE,
  M0_VALUE, M5_VALUE, M12_VALUE, M18_VALUE, M60_VALUE, MOTHER_VALUE, MTOTAL_VALUE, TOTAL_VALUE
from V_ASR_DEMOGRAPHICS_EN;

create index IX_DEME_YEAR on ASR_DEMOGRAPHICS_EN (ASR_YEAR);
create index IX_DEME_COU_RES on ASR_DEMOGRAPHICS_EN (COU_CODE_RESIDENCE);
create index IX_DEME_COU_OGN on ASR_DEMOGRAPHICS_EN (COU_CODE_ORIGIN);

--
-- ASR_RSD_EN
--
create materialized view ASR_RSD_EN as
select ASR_YEAR, COU_CODE_ASYLUM, COU_NAME_ASYLUM_EN, COU_CODE_ORIGIN, COU_NAME_ORIGIN_EN,
  RSD_PROC_TYPE_CODE, RSD_PROC_TYPE_DESCRIPTION_EN,
  RSD_PROC_LEVEL_CODE, RSD_PROC_LEVEL_DESCRIPTION_EN,
  ASYPOP_START_VALUE, ASYPOP_AH_START_VALUE,
  ASYAPP_VALUE, ASYREC_CV_VALUE, ASYREC_CP_VALUE, ASYREJ_VALUE, ASYOTHCL_VALUE,
  ASYPOP_END_VALUE, ASYPOP_AH_END_VALUE
from V_ASR_RSD_EN;

create index IX_RSDE_YEAR on ASR_RSD_EN (ASR_YEAR);
create index IX_RSDE_COU_ASY on ASR_RSD_EN (COU_CODE_ASYLUM);
create index IX_RSDE_COU_OGN on ASR_RSD_EN (COU_CODE_ORIGIN);