@dropall
@drop

spool RebuildStage.log

purge recyclebin;

@StageFunctions

@@S_ACCOM_TYPE_CORRECTIONS
@@S_BASIS_CORRECTIONS
@@S_CODE_TYPES
@@S_CODES
@@S_COMPONENTS
@@S_DIMENSION_TYPES
@@S_DIMENSION_VALUES
@@S_DISPLACEMENT_STATUSES
@@S_DST_CODE_CORRECTIONS
@@S_LANGUAGES
@@S_LOCATION_ATTRIBUTE_TYPES
@@S_LOCATION_COUNTRIES
@@S_LOCATION_COUNTRY_NAMES
@@S_LOCATION_NAME_CORRECTIONS
@@S_LOCATION_REGIONS
@@S_LOCATION_REGION_NAMES
@@S_LOCATION_RELATIONSHIPS
@@S_LOCATION_RELATIONSHIP_TYPES
@@S_LOCATION_SUBDIVISIONS
@@S_LOCATION_TYPES
@@S_LOCATION_TYPE_VARIANTS
@@S_MESSAGES
@@S_POPULATION_TYPE_CORRECTIONS
@@S_SOURCE_CORRECTIONS
@@S_STATISTIC_TYPES
@@S_STATISTIC_TYPES_IN_GROUPS
@@S_STATISTIC_TYPE_GROUPS
@@S_STC_GROUP_ATTRIBUTE_TYPES
@@S_TEXT_TYPES
@@S_TEXT_TYPE_PROPERTIES

@@S_PPG
@@S_PPG_CORRECTIONS

@@S_ASR_REFUGEES
@@S_ASR_DEMOGRAPHICS
@@S_ASR_RSD
@@S_ASR_IDPS
@@S_ASR_RETURNS
@@S_ASR_STATELESS
@@S_ASR_OOC

@@RefreshStageMViews

@@CheckStageIntegrity

spool off
