@dropall
@drop

spool RebuildStage.log

purge recyclebin;

@@S_LANGUAGES
@@S_STATISTIC_GROUPS
@@S_STATISTIC_TYPES
@@S_STATISTIC_TYPES_IN_GROUPS
@@S_DIMENSION_TYPES
@@S_DIMENSION_VALUES
@@S_LOCATION_TYPES
@@S_LOCATION_ATTRIBUTE_TYPES
@@S_LOCATION_RELATIONSHIP_TYPES
@@S_LOCATION_REGIONS
@@S_LOCATION_COUNTRIES
@@S_ASR_T2_2010
@@S_ASR_T2_2011
@@S_ASR_T5_2011
@@S_ASR_T7A_2011
@@S_ASR_T7B_2011
@@S_ASR_T7C_2004_2011
@@S_ASR_T7D_2006_2011

@@StageViews

spool off
