create view S_ASR_T2
 (STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DISPLACEMENT_STATUS,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select '2010' as STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DISPLACEMENT_STATUS,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T2_2010
union all
select '2011' as STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DISPLACEMENT_STATUS,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T2_2011;

grant select on S_ASR_T2 to PSR_STAGE;

create view S_ASR_T5
 (STATSYEAR,
  COU_CODE_ASYLUM,
  DIM_RSDTYPE_VALUE,
  PROCEDURE_LEVEL, APPLICATION_IND_GROUP, APPLICATION_GROUP_SIZE,
  DIM_RSDLEVEL_VALUE, DECISION_IND_GROUP, DECISION_GROUP_SIZE,
  COU_CODE_ORIGIN,
  ASY_START, ASY_AH_START,
  ASYAPP, ASYREC_CV, ASYREC_CP, ASYREJ, ASYOTHCL, TOTAL_DECISIONS,
  ASY_END, ASY_AH_END)
as
select '2011' as STATSYEAR,
  COU_CODE_ASYLUM,
  DIM_RSDTYPE_VALUE,
  PROCEDURE_LEVEL, APPLICATION_IND_GROUP, APPLICATION_GROUP_SIZE,
  DIM_RSDLEVEL_VALUE, DECISION_IND_GROUP, DECISION_GROUP_SIZE,
  COU_CODE_ORIGIN,
  ASY_START, ASY_AH_START,
  ASYAPP, ASYREC_CV, ASYREC_CP, ASYREJ, ASYOTHCL, TOTAL_DECISIONS,
  ASY_END, ASY_AH_END
from S_ASR_T5_2011;

grant select on S_ASR_T5 to PSR_STAGE;

create view S_ASR_T7AB
 (STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DST_CODE,
  RETURN, RETURN_AH,
  SOURCE, BASIS)
as
select '2011' as STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, 'REF' as DST_CODE,
  RETURN, RETURN_AH,
  SOURCE, BASIS
from S_ASR_T7A_2011
union all
select '2011' as STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, 'ROC' as DST_CODE,
  RETURN, RETURN_AH,
  SOURCE, BASIS
from S_ASR_T7B_2011;

grant select on S_ASR_T7AB to PSR_STAGE;

create view S_ASR_T7C
 (STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  NATLOSS, STAOTHINC, NATACQ, STAOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  NATLOSS, STAOTHINC, NATACQ, STAOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T7C_2004_2011;

grant select on S_ASR_T7C to PSR_STAGE;

create view S_ASR_T7D
 (STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  OOCARR, OOCOTHINC, OOCRTN, OOCOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select STATSYEAR,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  OOCARR, OOCOTHINC, OOCRTN, OOCOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T7D_2006_2011;

grant select on S_ASR_T7D to PSR_STAGE;
