create view S_ASR_T2
 (TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T2_2010
union all
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  POP_START, POP_AH_START,
  ARR_GRP, ARR_IND, ARR_RESTL, BIRTH, REFOTHINC, TOTAL_INCREASE,
  VOLREP, VOLREP_AH, RESTL, RESTL_AH, CESSATION, NATURLZN, DEATH, REFOTHDEC, TOTAL_DECREASE,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T2_2011;

grant select on S_ASR_T2 to PSR_STAGE;

create view S_ASR_T3
 (TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, LOCATION_NAME, NEW_LOCATION_NAME, COU_CODE_ORIGIN,
  URBAN_RURAL_STATUS, ACCOMMODATION_TYPE, PPG_NAME,
  F0_4, F5_11, F12_17, F18_59, F60, FOTHER, FTOTAL,
  M0_4, M5_11, M12_17, M18_59, M60, MOTHER, MTOTAL,
  TOTAL, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, LOCATION_NAME, NEW_LOCATION_NAME, COU_CODE_ORIGIN,
  URBAN_RURAL_STATUS, ACCOMMODATION_TYPE, PPG_NAME,
  F0_4, F5_11, F12_17, F18_59, F60, FOTHER, FTOTAL,
  M0_4, M5_11, M12_17, M18_59, M60, MOTHER, MTOTAL,
  TOTAL, BASIS
from S_ASR_T3_2010
union all
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, LOCATION_NAME, NEW_LOCATION_NAME, COU_CODE_ORIGIN,
  URBAN_RURAL_STATUS, ACCOMMODATION_TYPE, PPG_NAME,
  F0_4, F5_11, F12_17, F18_59, F60, FOTHER, FTOTAL,
  M0_4, M5_11, M12_17, M18_59, M60, MOTHER, MTOTAL,
  TOTAL, BASIS
from S_ASR_T3_2011;

grant select on S_ASR_T3 to PSR_STAGE;

create view S_ASR_T4
 (TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  UNCONV51, OAUCONV69, HCRSTAT, COMPPROT, TEMPPROT, OTHER, UNKNOWN, TOTAL)
as
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  UNCONV51, OAUCONV69, HCRSTAT, COMPPROT, TEMPPROT, OTHER, UNKNOWN, TOTAL
from S_ASR_T4_2010
union all
select TABLE_NUMBER, STATSYEAR, DISPLACEMENT_STATUS,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  UNCONV51, OAUCONV69, HCRSTAT, COMPPROT, TEMPPROT, OTHER, UNKNOWN, TOTAL
from S_ASR_T4_2011;

grant select on S_ASR_T4 to PSR_STAGE;

create view S_ASR_T5
 (TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  DIM_RSDTYPE_VALUE,
  PROCEDURE_LEVEL, APPLICATION_IND_GROUP, APPLICATION_GROUP_SIZE,
  DIM_RSDLEVEL_VALUE, DECISION_IND_GROUP, DECISION_GROUP_SIZE,
  ASY_START, ASY_AH_START,
  ASYAPP, ASYREC_CV, ASYREC_CP, ASYREJ, ASYOTHCL, TOTAL_DECISIONS,
  ASY_END, ASY_AH_END)
as
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  DIM_RSDTYPE_VALUE,
  PROCEDURE_LEVEL, APPLICATION_IND_GROUP, APPLICATION_GROUP_SIZE,
  DIM_RSDLEVEL_VALUE, DECISION_IND_GROUP, DECISION_GROUP_SIZE,
  ASY_START, ASY_AH_START,
  ASYAPP, ASYREC_CV, ASYREC_CP, ASYREJ, ASYOTHCL, TOTAL_DECISIONS,
  ASY_END, ASY_AH_END
from S_ASR_T5_2011;

grant select on S_ASR_T5 to PSR_STAGE;

create view S_ASR_T6
 (TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ORIGIN, LOCATION_NAME,
  DISPLACEMENT_CAUSE,
  POP_START, POP_AH_START,
  IDPNEW, IDPOTHINC, RETURN, RETURN_AH, IDPRELOC, IDPOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ORIGIN, LOCATION_NAME,
  DISPLACEMENT_CAUSE,
  POP_START, POP_AH_START,
  IDPNEW, IDPOTHINC, RETURN, RETURN_AH, IDPRELOC, IDPOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T6A_2006_2011
union all
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ORIGIN, LOCATION_NAME,
  DISPLACEMENT_CAUSE,
  POP_START, POP_AH_START,
  IDPNEW, IDPOTHINC, RETURN, RETURN_AH, IDPRELOC, IDPOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T6B_2007_2011
union all
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ORIGIN, LOCATION_NAME,
  DISPLACEMENT_CAUSE,
  POP_START, POP_AH_START,
  IDPNEW, IDPOTHINC, RETURN, RETURN_AH, IDPRELOC, IDPOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T6C_2006_2011
union all
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ORIGIN, LOCATION_NAME,
  DISPLACEMENT_CAUSE,
  POP_START, POP_AH_START,
  IDPNEW, IDPOTHINC, RETURN, RETURN_AH, IDPRELOC, IDPOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T6D_2011;

grant select on S_ASR_T6 to PSR_STAGE;

create view S_ASR_T7AB
 (TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  RETURN, RETURN_AH,
  SOURCE, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  RETURN, RETURN_AH,
  SOURCE, BASIS
from S_ASR_T7A_2011
union all
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN,
  RETURN, RETURN_AH,
  SOURCE, BASIS
from S_ASR_T7B_2011;

grant select on S_ASR_T7AB to PSR_STAGE;

create view S_ASR_T7C
 (TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  NATLOSS, STAOTHINC, NATACQ, STAOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  NATLOSS, STAOTHINC, NATACQ, STAOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T7C_2004_2011;

grant select on S_ASR_T7C to PSR_STAGE;

create view S_ASR_T7D
 (TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  OOCARR, OOCOTHINC, OOCRTN, OOCOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS)
as
select TABLE_NUMBER, STATSYEAR, DST_CODE,
  COU_CODE_ASYLUM, COU_CODE_ORIGIN, DESCRIPTION,
  POP_START, POP_AH_START,
  OOCARR, OOCOTHINC, OOCRTN, OOCOTHDEC,
  POP_END, POP_AH_END,
  SOURCE, BASIS
from S_ASR_T7D_2006_2011;

grant select on S_ASR_T7D to PSR_STAGE;
